<!DOCTYPE html>
<html lang="en">

<head>
  <base <?php echo BASE_URL ?>
    <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="icon" type="image/png" href="{BASE_URL}img/icons8-tyre-64.png">
  <!-- <link href="{BASE_URL}css/bootstrap.min.css" rel="stylesheet"> -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
  <!-- <link rel="stylesheet" href="'.BASE_URL.'TPE.css"> -->
  <title>Libreria Digital</title>
</head>

<body>
  <nav class="navbar navbar-expand-lg bg-dark navbar-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Libreria Digital</a>

      //<a href="home">Inicio</a>
      <a href="libros">Ver Libros</a>
      <a href="autores">Ver Autores</a>
      <?php if (isset($_SESSION['ID_USER'])): ?>
        <a href="logout">Cerrar Sesión</a>
      <?php else: ?>
        <a href="login">Login</a>
      <?php endif; ?>
  </nav>
</body>

</html>
